services:
  metabase:
    extends:
      file: docker-compose.yml
      service: metabase
    image: ""
    build:
      context: .
      dockerfile: metabase/Dockerfile

  client:
    extends:
      file: docker-compose.yml
      service: client

  server:
    extends:
      file: docker-compose.yml
      service: server
